from __future__ import annotations

import json
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

import streamlit as st
import streamlit.components.v1 as components


st.set_page_config(page_title="Mapa Punta Arenas", page_icon="🌎", layout="wide", initial_sidebar_state="collapsed")
st.markdown("""
<style>
html, body, #root, [data-testid="stAppViewContainer"], .stApp {width:100%!important;height:100dvh!important;min-height:100dvh!important;margin:0!important;padding:0!important;background:#f3f6f8!important;overflow:hidden!important}
[data-testid="stHeader"], [data-testid="stToolbar"], [data-testid="stDecoration"], #MainMenu, footer {display:none!important;height:0!important;visibility:hidden!important}
[data-testid="stMain"], [data-testid="stMainBlockContainer"] {position:relative!important;width:100vw!important;max-width:100vw!important;height:100dvh!important;min-height:100dvh!important;margin:0!important;padding:0!important}
[data-testid="stVerticalBlock"] {gap:0!important}
[data-testid="stElementContainer"]:has(iframe[title="st.iframe"]) {position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;margin:0!important;padding:0!important;z-index:1!important}
iframe[title="st.iframe"] {position:absolute!important;inset:0!important;display:block!important;width:100vw!important;height:100dvh!important;max-height:100dvh!important;border:0!important}
</style>
""", unsafe_allow_html=True)
DATA_DIR = Path(__file__).parent
KML_NS = {"k": "http://www.opengis.net/kml/2.2"}


@st.cache_data(show_spinner="Preparando las capas del mapa…")
def read_kmz(filename: str) -> dict:
    """Read regular KMZ archives and KML files mistakenly named .kmz."""
    path = DATA_DIR / filename
    raw = path.read_bytes()
    if raw[:2] == b"PK":
        with zipfile.ZipFile(path) as archive:
            kml_name = next(n for n in archive.namelist() if n.lower().endswith(".kml"))
            raw = archive.read(kml_name)
    # These two concession files declare UTF-8 but contain legacy Windows-1252 bytes.
    try:
        xml = raw.decode("utf-8")
        ET.fromstring(xml)  # Some malformed exports declare UTF-8 but contain cp1252 bytes.
    except (UnicodeDecodeError, ET.ParseError):
        xml = raw.decode("cp1252")
    root = ET.fromstring(xml)
    styles = {s.get("id"): s for s in root.findall(".//k:Document/k:Style", KML_NS)}
    style_maps = {}
    for style_map in root.findall(".//k:Document/k:StyleMap", KML_NS):
        for pair in style_map.findall("k:Pair", KML_NS):
            if pair.findtext("k:key", default="", namespaces=KML_NS) == "normal":
                style_maps[style_map.get("id")] = pair.findtext("k:styleUrl", default="", namespaces=KML_NS).lstrip("#")
    out = {"groups": {}, "polygons": []}

    def coordinates(node):
        text = node.findtext("k:coordinates", default="", namespaces=KML_NS)
        result = []
        for pair in text.split():
            bits = pair.split(",")
            if len(bits) >= 2:
                try:
                    result.append([float(bits[0]), float(bits[1])])
                except ValueError:
                    continue
        return result

    def group_for(placemark):
        folders = []
        parent = parents.get(placemark)
        while parent is not None:
            if parent.tag.rsplit("}", 1)[-1] == "Folder":
                folders.append(parent.findtext("k:name", default="", namespaces=KML_NS))
            parent = parents.get(parent)
        folders.reverse()
        return folders[1] if len(folders) > 1 else (folders[0] if folders else "Red eléctrica")

    parents = {child: parent for parent in root.iter() for child in parent}
    for placemark in root.findall(".//k:Placemark", KML_NS):
        name = placemark.findtext("k:name", default="", namespaces=KML_NS)
        description = placemark.findtext("k:description", default="", namespaces=KML_NS)
        style_id = placemark.findtext("k:styleUrl", default="", namespaces=KML_NS).lstrip("#")
        style_id = style_maps.get(style_id, style_id)
        style = styles.get(style_id)
        icon = style.findtext("k:IconStyle/k:Icon/k:href", default="", namespaces=KML_NS) if style is not None else ""
        point_color = style.findtext("k:IconStyle/k:color", default="", namespaces=KML_NS) if style is not None else ""
        line_color = style.findtext("k:LineStyle/k:color", default="", namespaces=KML_NS) if style is not None else ""
        if not point_color:
            point_color = placemark.findtext("k:Style/k:IconStyle/k:color", default="", namespaces=KML_NS)
        if not line_color:
            line_color = placemark.findtext("k:Style/k:LineStyle/k:color", default="", namespaces=KML_NS)

        def css_color(kml_color, fallback):
            value = (kml_color or "").strip().lstrip("#")
            if len(value) == 8:
                return "#" + value[6:8] + value[4:6] + value[2:4]
            return fallback

        group = group_for(placemark)
        bucket = out["groups"].setdefault(group, {"points": [], "lines": []})
        fallback = {"Postes": "#ffca28", "Equipos": "#26a69a", "Subestaciones": "#ab47bc", "Redes MT": "#2962ff", "Red BT": "#fdd835"}.get(group, "#607d8b")
        attributes = {}
        for data in placemark.findall(".//k:Data", KML_NS):
            value = data.findtext("k:value", default="", namespaces=KML_NS)
            if data.get("name") and value:
                attributes[data.get("name")] = value
        for data in placemark.findall(".//k:SimpleData", KML_NS):
            if data.get("name") and data.text:
                attributes[data.get("name")] = data.text.strip()
        props = {"name": name, "description": description, "icon": icon,
                 "attributes": attributes, "color": css_color(point_color, fallback), "line_color": css_color(line_color, fallback)}
        for point in placemark.findall(".//k:Point", KML_NS):
            c = coordinates(point)
            if c:
                bucket["points"].append({**props, "coordinates": c[0]})
        for line in placemark.findall(".//k:LineString", KML_NS):
            c = coordinates(line)
            if len(c) > 1:
                bucket["lines"].append({**props, "coordinates": c})
        for polygon in placemark.findall(".//k:Polygon", KML_NS):
            rings = [coordinates(r) for r in polygon.findall(".//k:LinearRing", KML_NS)]
            rings = [r for r in rings if len(r) > 2]
            if rings:
                out["polygons"].append({**props, "coordinates": rings})
    return out


NETWORK = "Punta Arenas.kmz"
CONCESSION_LT = "concesiones2025v3 corregidas menor a 15.kmz"
CONCESSION_GE = "concesiones2025v3 GEO superior a 14.kmz"

try:
    network = read_kmz(NETWORK)
    concession_lt = read_kmz(CONCESSION_LT)
    concession_ge = read_kmz(CONCESSION_GE)
except Exception as exc:
    st.error(f"No se pudieron preparar las capas: {exc}")
    st.stop()

layers = [
    {"id": "network-" + str(i), "name": name,
     "color": {"Equipos": "#26a69a", "Postes": "#ffca28", "Subestaciones": "#ab47bc", "Redes MT": "#ff3030", "Red BT": "#1646ff"}.get(name, "#607d8b"),
     "data": {"points": group["points"], "lines": group["lines"], "polygons": []}}
    for i, (name, group) in enumerate(network["groups"].items())
    if group["points"] or group["lines"]
]
layers += [
    {"id": "lt15", "name": "Concesión menor a 15", "color": "#26c6da",
     "data": {"points": [], "lines": [], "polygons": concession_lt["polygons"]}},
    {"id": "ge14", "name": "Concesión GEO superior a 14", "color": "#ff7043",
     "data": {"points": [], "lines": [], "polygons": concession_ge["polygons"]}},
]

# Keep raw feature attributes in the browser search index; Leaflet renders the
# dense electrical network through a shared Canvas renderer.
layers_json = json.dumps(layers, ensure_ascii=False, separators=(",", ":"))
html = r"""<!doctype html>
<html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<style>
*{box-sizing:border-box}html,body{margin:0;height:100%;font-family:Arial,sans-serif;color:#202124}#map{position:absolute;inset:0;background:#dbe5e5}
.panel{position:absolute;z-index:1000;top:12px;left:12px;width:min(340px,calc(100vw - 24px));max-height:calc(100% - 24px);overflow:auto;background:#fff;border-radius:12px;box-shadow:0 2px 12px #0003;padding:14px;transition:opacity .16s ease,transform .16s ease}
.panel.is-hidden{display:none}.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.panel-head-main{min-width:0}.panel-close,.panel-open{border:0;background:#f1f3f4;color:#3c4043;border-radius:9px;font-size:20px;line-height:1;cursor:pointer;touch-action:manipulation}.panel-close{flex:none;width:32px;height:32px;margin:-3px -3px 0 0}.panel-open{position:absolute;z-index:1002;top:12px;left:12px;padding:9px 12px;background:rgba(31,78,121,.78);color:#fff;backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);border:1px solid rgba(255,255,255,.55);box-shadow:0 2px 10px #0003;font-size:14px;font-weight:700;min-height:42px;min-width:44px}.panel-open[hidden]{display:none}
.leaflet-top.leaflet-left{top:auto;bottom:12px;left:12px}
.title{font-size:18px;font-weight:700;margin-bottom:3px}.sub{font-size:12px;color:#5f6368;margin-bottom:8px}.searchbox{margin:10px 0}.searchbox input{width:100%;padding:10px 11px;border:1px solid #dadce0;border-radius:9px;font-size:14px}.search-actions{display:flex;gap:6px;margin-top:7px}.search-actions button{flex:1;border:1px solid #dadce0;border-radius:8px;background:#fff;padding:8px 6px;font-weight:600;color:#3c4043}.search-actions button.active{background:#1f4e79;color:#fff;border-color:#1f4e79}.search-results{max-height:170px;overflow:auto}.result{width:100%;text-align:left;background:#fff;border:0;border-top:1px solid #eee;padding:9px 6px;font-size:13px;color:#202124}.result small{display:block;color:#70757a;margin-top:3px}.search-status{font-size:12px;color:#5f6368;margin:6px 2px}.layer-heading{font-size:12px;font-weight:700;color:#5f6368;margin-top:10px}.row{display:flex;align-items:center;gap:9px;padding:8px 4px;border-top:1px solid #eee;font-size:14px}.row input{width:18px;height:18px;accent-color:#4285f4}.swatch{width:11px;height:11px;border-radius:50%;flex:none}.count{display:block;color:#70757a;font-size:11px;margin-left:28px;margin-top:-6px;padding-bottom:7px}.map-style{position:absolute;z-index:1001;right:12px;bottom:34px;display:flex;padding:3px;gap:2px;background:rgba(255,255,255,.94);border:1px solid #d9dfe5;border-radius:12px;box-shadow:0 2px 10px #0003;backdrop-filter:blur(8px)}.map-style button{border:0;border-radius:9px;padding:9px 12px;background:transparent;color:#39434e;font-size:13px;font-weight:700;white-space:nowrap;cursor:pointer;touch-action:manipulation}.map-style button.active{background:#1f4e79;color:#fff}.map-style button:focus-visible{outline:2px solid #4285f4;outline-offset:1px}
.popup-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.popup-actions a,.popup-actions button{display:inline-flex;align-items:center;justify-content:center;min-height:32px;padding:6px 9px;border:1px solid #d5dde6;border-radius:7px;background:#f7f9fc;color:#174f82;font:600 12px Arial,sans-serif;text-decoration:none;cursor:pointer}.popup-actions button.selected{background:#e8f3ed;color:#17633e;border-color:#a9d5ba}.selection-bar{position:absolute;z-index:1002;left:50%;bottom:12px;transform:translateX(-50%);display:flex;align-items:center;gap:5px;padding:5px;background:rgba(255,255,255,.94);border:1px solid #d9dfe5;border-radius:12px;box-shadow:0 2px 10px #0003;backdrop-filter:blur(8px);white-space:nowrap}.selection-bar[hidden],.pole-modal[hidden]{display:none}.selection-bar button{border:0;border-radius:8px;padding:8px 10px;background:#1f4e79;color:#fff;font-size:12px;font-weight:700;cursor:pointer}.selection-bar #pole-selection-clear{background:transparent;color:#506070}.pole-modal{position:absolute;z-index:1100;inset:0;display:grid;place-items:center;padding:16px;background:#0005}.pole-modal-card{width:min(440px,calc(100vw - 28px));max-height:min(78vh,650px);overflow:auto;padding:16px;background:#fff;border-radius:14px;box-shadow:0 8px 30px #0005}.pole-modal-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.pole-modal-head h2{margin:0;font-size:17px}.pole-modal-head button{border:0;border-radius:7px;padding:7px 10px;background:#eef2f6;font-size:16px}.pole-modal-list{padding-left:22px;font-size:13px;line-height:1.55}.pole-modal-actions{display:flex;gap:8px}.pole-modal-actions button{flex:1;min-height:40px;border:0;border-radius:8px;background:#1f4e79;color:#fff;font-weight:700}
.route-panel[hidden],.nav-card[hidden]{display:none}.route-panel{margin:8px 0;padding:9px;background:#f3f6fa;border:1px solid #e3e8ef;border-radius:10px}.route-heading{font-size:14px;font-weight:700;margin-bottom:4px}.route-help{font-size:11px;color:#5f6368;margin-bottom:7px}.route-tools,.route-actions{display:flex;gap:6px;margin:6px 0}.route-tools button,.route-actions button,.route-stop-actions button{border:1px solid #d4dbe4;border-radius:7px;padding:7px 8px;background:#fff;color:#35404b;font-size:12px;font-weight:600;cursor:pointer;touch-action:manipulation}.route-tools button.active,.route-actions #route-calculate{background:#1f4e79;color:#fff;border-color:#1f4e79}.route-actions button{flex:1}.route-actions button:disabled{opacity:.45;cursor:default}.route-stop{display:flex;align-items:center;gap:6px;padding:6px 2px;border-top:1px solid #dfe4ea;font-size:12px}.route-stop-num{display:flex;align-items:center;justify-content:center;flex:none;width:22px;height:22px;border-radius:50%;background:#1f4e79;color:white;font-size:11px;font-weight:700}.route-stop-name{flex:1;min-width:0;overflow-wrap:anywhere}.route-stop-actions{display:flex;gap:2px}.route-stop-actions button{padding:4px 6px}.route-summary{font-size:12px;font-weight:700;padding:6px 2px}.route-guidance{max-height:180px;overflow:auto;border-top:1px solid #dfe4ea}.route-leg-title{font-size:11px;font-weight:700;color:#435267;padding:7px 2px 3px}.route-step{display:flex;gap:7px;padding:5px 2px;border-top:1px solid #e5e9ee;font-size:11px;line-height:1.35}.route-step.active{background:#e5effb;color:#123f73;font-weight:700}.route-step-icon{width:18px;flex:none;color:#1f4e79;font-size:15px;text-align:center}.route-step-text{flex:1}.route-step-distance{flex:none;color:#6b7480}.route-map-pin{display:flex;align-items:center;justify-content:center;width:27px;height:27px;border:2px solid white;border-radius:50%;background:#1f4e79;color:#fff;font-size:12px;font-weight:800;box-shadow:0 1px 5px #0007}.nav-card{position:absolute;z-index:1003;top:12px;left:50%;transform:translateX(-50%);width:min(420px,calc(100vw - 24px));padding:12px 14px;background:rgba(255,255,255,.97);border:1px solid #dce2e9;border-radius:14px;box-shadow:0 4px 18px #0004;backdrop-filter:blur(8px)}.nav-card-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:7px;color:#5f6874;font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.04em}.nav-card-actions{display:flex;gap:5px}.nav-card-actions button{border:1px solid #d4dbe4;border-radius:7px;background:#fff;color:#35404b;font-size:11px;font-weight:600;padding:5px 8px;cursor:pointer}.nav-primary{font-size:19px;line-height:1.25;font-weight:700;color:#202124}.nav-secondary{margin-top:5px;font-size:13px;line-height:1.3;color:#596574}
.icon-key{display:flex;flex-wrap:wrap;gap:5px 10px;margin:2px 0 9px;font-size:11px;color:#48515c}.icon-key span{display:inline-flex;align-items:center;gap:4px}.key-icon{width:17px;height:17px;display:inline-flex;align-items:center;justify-content:center;border:1.5px solid #273444;color:white;font-size:10px;font-weight:800;background:#607d8b;border-radius:50%;font-style:normal}.key-post{background:#ffca28;color:#4b3b0b}.key-f{background:#ef6c00;border-radius:3px}.key-d{background:#008fa1;transform:rotate(45deg);border-radius:2px}.key-d b{transform:rotate(-45deg)}.key-r{background:#c62828}.key-se{background:#7b1fa2;border-radius:3px;font-size:8px}
@media(max-width:600px){.panel{top:8px;left:8px;padding:9px;width:min(276px,calc(100vw - 64px));max-height:52vh;border-radius:10px}.title{font-size:15px}.sub{font-size:11px;margin-bottom:5px}.panel-close{width:30px;height:30px}.row{padding:5px 3px;font-size:13px}.count{padding-bottom:4px}.searchbox{margin:6px 0}.searchbox input{padding:9px;font-size:16px}.search-actions button{padding:7px 4px;font-size:11px}.search-results{max-height:105px}.icon-key{gap:4px 6px;margin-bottom:5px;font-size:10px}.key-icon{width:16px;height:16px}.layer-heading{margin-top:7px}.panel-open{top:8px;left:8px;padding:8px 10px;min-height:40px}.leaflet-top.leaflet-left{bottom:12px;left:10px}.map-style{right:8px;bottom:38px;padding:2px}.map-style button{padding:8px 9px;font-size:12px}.route-panel{margin:6px 0;padding:7px}.route-tools button,.route-actions button{padding:7px 5px;font-size:11px}.route-guidance{max-height:125px}.nav-card{top:8px;padding:10px 12px}.nav-primary{font-size:17px}.nav-secondary{font-size:12px}.selection-bar{bottom:84px}}
  </style></head><body>
<div id="map"></div>
<div class="panel" id="layer-panel"><div class="panel-head"><div class="panel-head-main"><div class="title">🌎 Punta Arenas</div><div class="sub">Símbolos eléctricos · pulsa un activo para ver sus datos</div></div><button class="panel-close" id="panel-close" type="button" aria-label="Cerrar búsqueda y capas" title="Ocultar panel">×</button></div>
<div class="icon-key"><span><i class="key-icon key-post">┼</i>Poste</span><span><i class="key-icon key-f">F</i>Fusible</span><span><i class="key-icon key-d"><b>D</b></i>Desconectador</span><span><i class="key-icon key-r">R</i>Reconectador</span><span><i class="key-icon key-se">SE</i>Subestación</span></div>
<div class="searchbox"><input id="search" type="search" placeholder="Buscar poste, equipo, dirección o coordenadas"><div class="search-actions"><button id="search-go">Buscar</button><button id="gps">◎ Mi ubicación</button><button id="route-toggle" type="button" aria-expanded="false">🧭 Ruta</button></div><div class="search-status" id="search-status">Ej.: equipo F, D, R o SE · también puedes buscar direcciones</div><div class="search-results" id="search-results"></div></div>
<div class="route-panel" id="route-panel" hidden><div class="route-heading">Plan de ruta</div><div class="route-help" id="route-help">Busca un lugar o activo y selecciónalo, o añade paradas tocando el mapa.</div><div class="route-tools"><button id="route-map-add" type="button">＋ Añadir en mapa</button><button id="route-add-gps" type="button">◎ Mi ubicación</button></div><div id="route-stops"></div><div class="route-actions"><button id="route-calculate" type="button">Calcular ruta</button><button id="route-start" type="button" disabled>▶ Iniciar</button><button id="route-clear" type="button">Borrar</button></div><div class="route-summary" id="route-summary"></div><div class="route-guidance" id="route-guidance"></div></div>
<div class="layer-heading">Capas</div><div id="layer-list"></div></div>
<button class="panel-open" id="panel-open" type="button" aria-label="Abrir búsqueda y capas" title="Mostrar búsqueda y capas" hidden>⌕ Buscar / capas</button>
<div class="nav-card" id="nav-card" role="status" aria-live="polite" hidden><div class="nav-card-head"><span>Ruta activa</span><span class="nav-card-actions"><button id="nav-recenter" type="button">◎ Centrar</button><button id="nav-stop" type="button">Terminar</button></span></div><div class="nav-primary" id="nav-primary">Buscando tu ubicación…</div><div class="nav-secondary" id="nav-secondary"></div></div>
<div class="map-style" role="group" aria-label="Estilo del mapa"><button id="style-satellite" type="button" aria-pressed="true">🛰️ Satélite</button><button id="style-streets" type="button" aria-pressed="false">🗺️ Normal</button></div>
<div class="selection-bar" id="selection-bar" hidden><button id="pole-selection-open" type="button">Postes seleccionados: 0</button><button id="pole-selection-clear" type="button" aria-label="Limpiar selección">×</button></div>
<div class="pole-modal" id="pole-modal" hidden><section class="pole-modal-card" role="dialog" aria-modal="true" aria-labelledby="pole-modal-title"><div class="pole-modal-head"><h2 id="pole-modal-title">Postes seleccionados</h2><button id="pole-modal-close" type="button" aria-label="Cerrar">×</button></div><p id="pole-modal-count"></p><ol id="pole-modal-list" class="pole-modal-list"></ol><div class="pole-modal-actions"><button id="pole-copy" type="button">Copiar resumen</button><button id="pole-modal-done" type="button">Cerrar</button></div></section></div>
<script>
const layers=__LAYERS__;
const osm=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'});
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Tiles © Esri'});
const map=L.map('map',{preferCanvas:true,doubleClickZoom:false,layers:[satellite]}).setView([-53.15,-70.92],10);
const renderer=L.canvas({padding:0.5});let satelliteOn=true,gpsMarker=null,selectedMarker=null,routeMode=false,routeAddMode=false,routeStops=[],routeMarkers=[],routeLine=null;const panel=document.getElementById('layer-panel'),openPanelButton=document.getElementById('panel-open'),searchInput=document.getElementById('search'),searchStatus=document.getElementById('search-status'),searchResults=document.getElementById('search-results'),routePanel=document.getElementById('route-panel'),routeStopsEl=document.getElementById('route-stops'),routeSummary=document.getElementById('route-summary'),routeGuidance=document.getElementById('route-guidance'),routeHelp=document.getElementById('route-help'),routeStartButton=document.getElementById('route-start'),navCard=document.getElementById('nav-card'),navPrimary=document.getElementById('nav-primary'),navSecondary=document.getElementById('nav-secondary');let searchIndex=[],routeInstructions=[],navStepIndex=0,navWatchId=null,navPositionMarker=null,navCurrentLocation=null,navigationActive=false,followNavigation=true;
const poleSelection=new Map(),poleSelectionRings=new Map(),selectionBar=document.getElementById('selection-bar'),poleModal=document.getElementById('pole-modal'),poleModalList=document.getElementById('pole-modal-list');
function hidePanel(){panel.classList.add('is-hidden');openPanelButton.hidden=false}
function showPanel(){panel.classList.remove('is-hidden');openPanelButton.hidden=true}
L.DomEvent.disableClickPropagation(panel);L.DomEvent.disableScrollPropagation(panel);L.DomEvent.disableClickPropagation(openPanelButton);
document.getElementById('panel-close').onclick=hidePanel;openPanelButton.onclick=showPanel;map.on('click',e=>{if(routeAddMode){addRouteStop('Punto '+(routeStops.length+1),[e.latlng.lat,e.latlng.lng]);return}hidePanel()});
const routeToggle=document.getElementById('route-toggle'),routeMapAdd=document.getElementById('route-map-add');routeToggle.onclick=()=>{routeMode=!routeMode;routePanel.hidden=!routeMode;routeToggle.classList.toggle('active',routeMode);routeToggle.setAttribute('aria-expanded',String(routeMode));if(routeMode){showPanel();routeHelp.textContent='Busca una dirección o activo y selecciónalo. También puedes añadir varios puntos tocando el mapa.'}else{routeAddMode=false;routeMapAdd.classList.remove('active')}};routeMapAdd.onclick=()=>{routeAddMode=!routeAddMode;routeMapAdd.classList.toggle('active',routeAddMode);routeHelp.textContent=routeAddMode?'Toca el mapa para añadir paradas. Pulsa de nuevo para terminar.':'Busca una dirección o activo y selecciónalo, o añade paradas tocando el mapa.'};document.getElementById('route-calculate').onclick=calculateRoute;document.getElementById('route-clear').onclick=clearRoute;document.getElementById('route-add-gps').onclick=addGpsStop;routeStartButton.onclick=startNavigation;document.getElementById('nav-stop').onclick=stopNavigation;document.getElementById('nav-recenter').onclick=()=>{if(navCurrentLocation){followNavigation=true;map.panTo(navCurrentLocation,{animate:true,duration:.4})}};map.on('dragstart',()=>{if(navigationActive){followNavigation=false;document.getElementById('nav-recenter').hidden=false}});
function symbolType(layer,attrs={}){if(layer==='Postes')return 'poste';if(layer==='Subestaciones')return 'se';if(layer==='Equipos'){const t=norm(attrs.TIPO_LMDS);if(t.includes('fusible'))return 'fuse';if(t.includes('desconectador'))return 'disconnect';if(t.includes('reconectador'))return 'recloser'}return ''}
const originalCircle=renderer._updateCircle;renderer._updateCircle=function(layer){const type=layer.options.assetIcon;if(!type)return originalCircle.call(this,layer);if(!this._drawing||layer._empty())return;const ctx=this._ctx,p=layer._point,z=map.getZoom(),r=z>=15?9.5:z>=13?7:3.2;const colors={poste:'#ffca28',fuse:'#ef6c00',disconnect:'#008fa1',recloser:'#c62828',se:'#7b1fa2'};ctx.save();ctx.translate(p.x,p.y);ctx.lineWidth=z>=15?1.7:z>=13?1.2:0.8;ctx.strokeStyle=z>=13?'#25313e':'#fff';ctx.fillStyle=colors[type]||'#607d8b';ctx.beginPath();if(z<13)ctx.arc(0,0,r,0,Math.PI*2);else if(type==='disconnect'){ctx.moveTo(0,-r);ctx.lineTo(r,0);ctx.lineTo(0,r);ctx.lineTo(-r,0);ctx.closePath()}else if(type==='fuse'||type==='se'){ctx.rect(-r*.82,-r*.82,r*1.64,r*1.64)}else ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.stroke();if(z>=13){ctx.strokeStyle=type==='poste'?'#59420b':'#fff';ctx.fillStyle=type==='poste'?'#59420b':'#fff';ctx.lineWidth=z>=15?1.8:1.2;ctx.lineCap='round';ctx.lineJoin='round';if(type==='poste'){ctx.beginPath();ctx.moveTo(0,-r*.72);ctx.lineTo(0,r*.72);ctx.moveTo(-r*.68,-r*.25);ctx.lineTo(r*.68,-r*.25);ctx.moveTo(-r*.38,-r*.48);ctx.lineTo(r*.38,-r*.48);ctx.stroke()}else if(type==='fuse'){ctx.beginPath();ctx.moveTo(-r*.48,-r*.42);ctx.lineTo(r*.48,-r*.42);ctx.moveTo(-r*.48,r*.42);ctx.lineTo(r*.48,r*.42);ctx.moveTo(0,-r*.42);ctx.lineTo(0,r*.42);ctx.stroke();if(z>=15){ctx.font='bold 10px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('F',0,r*.66)}}else if(type==='disconnect'){ctx.beginPath();ctx.moveTo(-r*.48,r*.45);ctx.lineTo(r*.4,-r*.42);ctx.moveTo(r*.32,-r*.48);ctx.lineTo(r*.56,-r*.3);ctx.stroke();ctx.beginPath();ctx.arc(-r*.53,r*.52,r*.13,0,Math.PI*2);ctx.fill();if(z>=15){ctx.font='bold 10px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('D',0,r*.63)}}else if(type==='recloser'){ctx.beginPath();ctx.arc(0,0,r*.43,-Math.PI*.78,Math.PI*.78);ctx.moveTo(-r*.22,-r*.45);ctx.lineTo(-r*.48,-r*.38);ctx.lineTo(-r*.37,-r*.13);ctx.stroke();if(z>=15){ctx.font='bold 10px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('R',0,r*.08)}}else if(type==='se'){ctx.beginPath();ctx.moveTo(-r*.52,r*.42);ctx.lineTo(-r*.52,-r*.15);ctx.lineTo(0,-r*.56);ctx.lineTo(r*.52,-r*.15);ctx.lineTo(r*.52,r*.42);ctx.moveTo(-r*.22,r*.42);ctx.lineTo(-r*.22,r*.05);ctx.lineTo(r*.22,r*.05);ctx.lineTo(r*.22,r*.42);ctx.stroke();if(z>=15){ctx.fillStyle='#fff';ctx.font='bold 6px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('SE',0,r*.68)}}}ctx.restore()};
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function localCodeNumber(v){const s=String(v||'').trim();return /^10\d+$/.test(s)?s.slice(2):s}
function substationNumber(v){return localCodeNumber(v)}
function feederNumber(v){return localCodeNumber(v)}
function searchableAttrs(a={}){return Object.entries(a).map(([k,v])=>[/^(SE|SUBESTACION|ALIMENTADOR|ALIMENTADOR_ID)$/i.test(k)?localCodeNumber(v):v,v]).flat().join(' ')}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function mapsPointUrl(coord){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(coord[0]+','+coord[1])}
function feederFor(attrs={}){return attrs.ALIMENTADOR||attrs.ALIMENTADOR_ID||''}
function substationFor(attrs={}){return attrs.SUBESTACION||attrs.SE||''}
function poleKey(coord,attrs={}){return String(attrs.POSTE_ID||attrs.IDENTIFICADOR_VNR||'')+'|'+coord[0].toFixed(6)+','+coord[1].toFixed(6)}
function popupActions(layer,attrs,coord){const maps='<a href="'+mapsPointUrl(coord)+'" target="_blank" rel="noopener noreferrer">↗ Ver en Maps</a>';if(layer!=='Postes')return '<div class="popup-actions">'+maps+'</div>';const key=poleKey(coord,attrs),selected=poleSelection.has(key);return '<div class="popup-actions">'+maps+'<button type="button" data-pole-key="'+key+'" class="'+(selected?'selected':'')+'">'+(selected?'✓ Poste seleccionado':'＋ Seleccionar poste')+'</button></div>'}
function wirePoleButton(marker,attrs,name,coord){marker.on('popupopen',()=>{const button=marker.getPopup().getElement()?.querySelector('[data-pole-key]');if(button)button.onclick=()=>{togglePoleSelection(button.dataset.poleKey,attrs.IDENTIFICADOR_VNR||attrs.POSTE_ID||name||'Poste',attrs,coord);button.classList.toggle('selected',poleSelection.has(button.dataset.poleKey));button.textContent=poleSelection.has(button.dataset.poleKey)?'✓ Poste seleccionado':'＋ Seleccionar poste'}})}
function wireAssetPopup(marker,layer,attrs,name,coord){marker.bindPopup(assetHeading(layer,attrs,name)+popupFields(layer,attrs)+popupActions(layer,attrs,coord));if(layer==='Postes')wirePoleButton(marker,attrs,name,coord)}
function togglePoleSelection(key,title,attrs,coord){if(poleSelection.has(key)){poleSelection.delete(key);const ring=poleSelectionRings.get(key);if(ring)map.removeLayer(ring);poleSelectionRings.delete(key)}else{poleSelection.set(key,{title,feeder:feederFor(attrs),substation:substationFor(attrs)});poleSelectionRings.set(key,L.circleMarker(coord,{renderer,radius:13,color:'#087443',weight:3,fillOpacity:0,interactive:false}).addTo(map))}updatePoleSelectionUI()}
function poleSummaryText(){const rows=[`Postes seleccionados: ${poleSelection.size}`];for(const [i,p] of [...poleSelection.values()].entries())rows.push(`${i+1}. ${p.title} | Alimentador: ${p.feeder?feederNumber(p.feeder):'sin dato en KMZ'} | Subestación: ${p.substation?substationNumber(p.substation):'sin dato en KMZ'}`);return rows.join('\n')}
function updatePoleSelectionUI(){const count=poleSelection.size;selectionBar.hidden=!count;document.getElementById('pole-selection-open').textContent=count+' poste'+(count===1?' seleccionado':'s seleccionados');document.getElementById('pole-modal-count').textContent=count+' poste'+(count===1?'':'s')+' seleccionado'+(count===1?'':'s');poleModalList.replaceChildren();for(const p of poleSelection.values()){const li=document.createElement('li');li.textContent=p.title+' — Alimentador: '+(p.feeder?feederNumber(p.feeder):'sin dato en KMZ')+' — Subestación: '+(p.substation?substationNumber(p.substation):'sin dato en KMZ');poleModalList.appendChild(li)}}
function clearPoleSelection(){for(const ring of poleSelectionRings.values())map.removeLayer(ring);poleSelectionRings.clear();poleSelection.clear();updatePoleSelectionUI()}
document.getElementById('pole-selection-open').onclick=()=>{updatePoleSelectionUI();poleModal.hidden=false};document.getElementById('pole-selection-clear').onclick=clearPoleSelection;document.getElementById('pole-modal-close').onclick=document.getElementById('pole-modal-done').onclick=()=>{poleModal.hidden=true};poleModal.addEventListener('click',e=>{if(e.target===poleModal)poleModal.hidden=true});document.getElementById('pole-copy').onclick=async()=>{try{await navigator.clipboard.writeText(poleSummaryText());document.getElementById('pole-copy').textContent='Copiado'}catch{const area=document.createElement('textarea');area.value=poleSummaryText();document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();document.getElementById('pole-copy').textContent='Copiado'}setTimeout(()=>document.getElementById('pole-copy').textContent='Copiar resumen',1600)};
function popupFields(layer,attrs){const fields=[],put=(label,...keys)=>{for(const key of keys){const value=attrs[key];if(value!==undefined&&String(value).trim()&&!['0','#N/D','null'].includes(String(value).trim())){fields.push([label,String(value).trim()]);return}}},putSubstation=(...keys)=>{for(const key of keys){const value=attrs[key];if(value!==undefined&&String(value).trim()){fields.push(['Subestación',substationNumber(value)]);return}}},putFeeder=(...keys)=>{for(const key of keys){const value=attrs[key];if(value!==undefined&&String(value).trim()){fields.push(['Alimentador',feederNumber(value)]);return}}};
 if(layer==='Postes'){put('N° de poste','IDENTIFICADOR_VNR','POSTE_ID');putSubstation('SUBESTACION','SE');putFeeder('ALIMENTADOR','ALIMENTADOR_ID');let voltage=attrs['TIPO_TENSION_ID'];if(voltage){const v=String(voltage).trim().toUpperCase();if(v==='MT'||v==='BT')fields.push(['Red',v]);else if(v==='AMBAS'||v==='MT/BT'||v==='BT/MT')fields.push(['Red','MT y BT'])}}
 else if(layer==='Equipos'){put('Tipo','TIPO_LMDS');putSubstation('SUBESTACION','SE');putFeeder('ALIMENTADOR_ID')}
 else if(layer==='Subestaciones'){putFeeder('ALIMENTADOR_ID');put('Potencia (kVA)','KVA')}
 else if(layer==='Redes MT'){put('Tramo MT','TRAMO_MT_ID');putFeeder('ALIMENTADOR_ID');put('Longitud (m)','LARGO_RED')}
 else if(layer==='Red BT'){put('Tramo BT','TRAMO_BT_ID');putFeeder('ALIMENTADOR_ID');put('Longitud (m)','LARGO_RED')}
 else for(const [k,v] of Object.entries(attrs).filter(([k])=>k.toUpperCase()!=='CODIGO_VNR').slice(0,8))if(v)fields.push([k,v]);return fields.map(([k,v])=>'<div><b>'+esc(k)+':</b> '+esc(v)+'</div>').join('')}
function assetTitle(layer,a,name){if(name&&layer!=='Subestaciones')return name;if(layer==='Postes')return a.IDENTIFICADOR_VNR||a.POSTE_ID||layer;if(layer==='Equipos')return a.DENOMINACION||a.EQUIPO_ID||layer;if(layer==='Subestaciones')return substationNumber(a.SE)||layer;if(layer==='Redes MT')return a.TRAMO_MT_ID||layer;if(layer==='Red BT')return a.TRAMO_BT_ID||layer;return a.NOMBRE_CONCESION||a.ID||Object.values(a)[0]||layer}
function assetSubtitle(layer,a){if(layer==='Postes')return a.TIPO_TENSION_ID||'';if(layer==='Equipos')return a.TIPO_LMDS||'';if(layer==='Subestaciones')return a.ALIMENTADOR_ID?'Alim. '+feederNumber(a.ALIMENTADOR_ID):'';if(layer==='Redes MT'||layer==='Red BT')return [a.ALIMENTADOR_ID?'Alim. '+feederNumber(a.ALIMENTADOR_ID):'',a.LARGO_RED?a.LARGO_RED+' m':''].filter(Boolean).join(' · ');return a.NOMBRE_CONCESION||''}
function assetHeading(layer,attrs={},name=''){if(layer==='Postes')return poleGlyph+'<b>Poste</b>';if(layer==='Equipos')return '<b>'+esc(assetTitle(layer,attrs,name)||'Equipo')+'</b>';if(layer==='Subestaciones')return '<b>Subestación '+esc(substationNumber(attrs.SE)||assetTitle(layer,attrs,name))+'</b>';return '<b>'+esc(assetTitle(layer,attrs,name)||layer)+'</b>'}
const poleGlyph='<svg aria-hidden="true" width="19" height="25" viewBox="0 0 19 25" style="vertical-align:middle;margin-right:5px"><path d="M9.5 4v18M3 7h13M5 4h9M6 7l-2 3m9-3 2 3" fill="none" stroke="#765313" stroke-width="2" stroke-linecap="round"/><circle cx="9.5" cy="4" r="2" fill="#ffca28" stroke="#765313" stroke-width="1.2"/></svg>';
function coordOf(g){if(g.type==='Point')return [g.coordinates[1],g.coordinates[0]];if(g.type==='LineString'){const c=g.coordinates[Math.floor(g.coordinates.length/2)];return [c[1],c[0]]}if(g.type==='Polygon'){const r=g.coordinates[0]||[];if(!r.length)return null;return [r.reduce((a,c)=>a+c[1],0)/r.length,r.reduce((a,c)=>a+c[0],0)/r.length]}return null}
function goTo(item){const c=coordOf(item.geometry);if(!c)return;hidePanel();if(selectedMarker)selectedMarker.remove();const target=L.circleMarker(c,{renderer,radius:10,color:'#fff',weight:2,fillColor:'#4285f4',fillOpacity:1,assetIcon:symbolType(item.layer,item.attrs||{})}).addTo(map);selectedMarker=target;wireAssetPopup(target,item.layer,item.attrs||{},item.title,c);const point=L.latLng(c[0],c[1]),alreadyThere=map.getZoom()===17&&map.getCenter().distanceTo(point)<2;if(alreadyThere)target.openPopup();else map.once('moveend',()=>target.openPopup());map.flyTo(c,17,{duration:0.9})}
function stopNavigation(){if(navWatchId!==null&&navigator.geolocation)navigator.geolocation.clearWatch(navWatchId);navWatchId=null;navigationActive=false;followNavigation=true;navCard.hidden=true;if(navPositionMarker){map.removeLayer(navPositionMarker);navPositionMarker=null}navCurrentLocation=null;routeStartButton.disabled=routeInstructions.length===0;routeStartButton.textContent='▶ Iniciar';document.getElementById('nav-recenter').hidden=true;showPanel()}
function clearRouteLine(){stopNavigation();if(routeLine){map.removeLayer(routeLine);routeLine=null}routeInstructions=[];routeStartButton.disabled=true;routeStartButton.textContent='▶ Iniciar';routeSummary.textContent='';routeGuidance.innerHTML=''}
function refreshRouteStops(){routeMarkers.forEach(m=>map.removeLayer(m));routeMarkers=[];routeStopsEl.innerHTML='';routeStops.forEach((stop,i)=>{const marker=L.marker(stop.coord,{icon:L.divIcon({className:'',html:'<span class="route-map-pin">'+(i+1)+'</span>',iconSize:[27,27],iconAnchor:[13,13]})}).addTo(map).bindPopup('<b>'+esc(i===0?'Inicio':i===routeStops.length-1?'Destino':'Parada '+(i+1))+':</b> '+esc(stop.name)+popupActions(stop.item?.layer||'Lugar',stop.item?.attrs||{},stop.coord));if(stop.item?.layer==='Postes')wirePoleButton(marker,stop.item.attrs||{},stop.name,stop.coord);routeMarkers.push(marker);const row=document.createElement('div');row.className='route-stop';const num=document.createElement('span');num.className='route-stop-num';num.textContent=String(i+1);const name=document.createElement('span');name.className='route-stop-name';name.textContent=stop.name;const actions=document.createElement('span');actions.className='route-stop-actions';for(const [label,title,delta] of [['↑','Subir parada',-1],['↓','Bajar parada',1]]){const b=document.createElement('button');b.type='button';b.textContent=label;b.title=title;b.setAttribute('aria-label',title);b.disabled=i+delta<0||i+delta>=routeStops.length;b.onclick=()=>{const j=i+delta;[routeStops[i],routeStops[j]]=[routeStops[j],routeStops[i]];clearRouteLine();refreshRouteStops()};actions.appendChild(b)}const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.title='Quitar parada';remove.setAttribute('aria-label','Quitar '+stop.name);remove.onclick=()=>{routeStops.splice(i,1);clearRouteLine();refreshRouteStops()};actions.appendChild(remove);row.append(num,name,actions);routeStopsEl.appendChild(row)});routeHelp.textContent=(routeAddMode?'Toca el mapa para seguir añadiendo. ':'')+(routeStops.length<2?'Añade al menos dos paradas para calcular la ruta.':routeStops.length+' paradas en orden · cambia el orden con ↑ y ↓.')}
function addRouteStop(name,coord,item=null){if(!coord||!Number.isFinite(coord[0])||!Number.isFinite(coord[1]))return;if(routeStops.length>=25){routeHelp.textContent='Puedes incluir hasta 25 paradas en una ruta.';return}routeMode=true;routePanel.hidden=false;routeToggle.classList.add('active');routeToggle.setAttribute('aria-expanded','true');showPanel();routeStops.push({name:String(name||'Punto '+(routeStops.length+1)),coord,item});clearRouteLine();refreshRouteStops()}
function clearRoute(){routeStops=[];routeAddMode=false;routeMapAdd.classList.remove('active');clearRouteLine();refreshRouteStops();routeHelp.textContent='Busca un lugar o activo y selecciónalo, o añade paradas tocando el mapa.'}
function addGpsStop(){if(!navigator.geolocation){routeHelp.textContent='Este navegador no ofrece GPS.';return}routeHelp.textContent='Solicitando ubicación al navegador…';navigator.geolocation.getCurrentPosition(pos=>addRouteStop('Mi ubicación',[pos.coords.latitude,pos.coords.longitude]),err=>{routeHelp.textContent=err.code===1?'Permite la ubicación para añadir el inicio.':'No se pudo obtener la ubicación GPS.'},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function googleMapsRouteUrl(){if(routeStops.length<2)return mapsPointUrl(routeStops[0]?.coord||[-53.15,-70.92]);const params=new URLSearchParams({api:'1',origin:routeStops[0].coord.join(','),destination:routeStops[routeStops.length-1].coord.join(','),travelmode:'driving'});if(routeStops.length>2)params.set('waypoints',routeStops.slice(1,-1).map(p=>p.coord.join(',')).join('|'));return 'https://www.google.com/maps/dir/?'+params.toString()}
function formatDistance(m){return m<1000?Math.round(m)+' m':(m/1000).toLocaleString('es-CL',{maximumFractionDigits:1})+' km'}
function formatDuration(s){const mins=Math.round(s/60);return mins<60?mins+' min':Math.floor(mins/60)+' h '+(mins%60)+' min'}
function turnText(step){const m=step.maneuver||{},mod=(m.modifier||'').replace(/_/g,' '),dirs={'slight left':'levemente a la izquierda','left':'a la izquierda','sharp left':'cerradamente a la izquierda','slight right':'levemente a la derecha','right':'a la derecha','sharp right':'cerradamente a la derecha','straight':'recto','uturn':'en U'},verb={'depart':'Parte','arrive':'Llegaste al destino','turn':'Gira','continue':'Continúa','new name':'Continúa','merge':'Incorpórate','on ramp':'Entra por la rampa','off ramp':'Sal por la rampa','fork':'Toma la bifurcación','end of road':'Al final de la vía, gira','roundabout':'Entra en la rotonda','rotary':'Entra en la rotonda','roundabout turn':'En la rotonda','exit roundabout':'Sal de la rotonda','exit rotary':'Sal de la rotonda','notification':'Continúa'};let text=verb[m.type]||'Continúa';if(dirs[mod]&&['turn','fork','end of road','roundabout turn'].includes(m.type))text+=' '+dirs[mod];if(m.exit!==undefined&&String(m.type).includes('roundabout'))text+=' (salida '+m.exit+')';if(step.name)text+=(m.type==='depart'?' por ':' por ')+step.name;return text}
function stepArrow(step){const m=step.maneuver||{},type=m.type||'',mod=m.modifier||'';if(type==='arrive')return '◎';if(type==='depart')return '●';if(type.includes('roundabout'))return '⟳';if(mod.includes('left'))return '↖';if(mod.includes('right'))return '↗';if(mod==='uturn')return '↩';return '↑'}
async function calculateRoute(){if(routeStops.length<2){routeHelp.textContent='Añade el punto de inicio y al menos un destino.';return}const btn=document.getElementById('route-calculate');btn.disabled=true;btn.textContent='Calculando…';routeHelp.textContent='Buscando el mejor recorrido en auto…';clearRouteLine();try{const coords=routeStops.map(p=>p.coord[1]+','+p.coord[0]).join(';'),url='https://router.project-osrm.org/route/v1/driving/'+coords+'?overview=full&geometries=geojson&steps=true&alternatives=false',response=await fetch(url,{signal:AbortSignal.timeout(25000)}),data=await response.json();if(!response.ok||data.code!=='Ok'||!data.routes?.length)throw new Error(data.message||data.code||'No hay una ruta disponible');const route=data.routes[0];routeLine=L.geoJSON(route.geometry,{style:{color:'#0759d5',weight:6,opacity:.9,lineCap:'round',lineJoin:'round'}}).addTo(map);routeMarkers.forEach(m=>m.bringToFront());map.fitBounds(routeLine.getBounds().pad(.12),{maxZoom:16});routeSummary.textContent=formatDistance(route.distance)+' · '+formatDuration(route.duration)+' · '+(routeStops.length-1)+' tramos';routeGuidance.innerHTML='';routeInstructions=[];route.legs.forEach((leg,i)=>{const heading=document.createElement('div');heading.className='route-leg-title';heading.textContent=(i===0?'Inicio':('Parada '+(i+1)))+': '+routeStops[i].name+' → '+routeStops[i+1].name;routeGuidance.appendChild(heading);for(const step of leg.steps||[]){const loc=step.maneuver?.location;if(!loc||!Number.isFinite(loc[0])||!Number.isFinite(loc[1]))continue;routeInstructions.push({step,coord:[loc[1],loc[0]]});const row=document.createElement('div');row.className='route-step';row.dataset.routeInstruction=String(routeInstructions.length-1);const icon=document.createElement('span');icon.className='route-step-icon';icon.textContent=stepArrow(step);const text=document.createElement('span');text.className='route-step-text';text.textContent=turnText(step);const distance=document.createElement('span');distance.className='route-step-distance';distance.textContent=formatDistance(step.distance||0);row.append(icon,text,distance);routeGuidance.appendChild(row)}});routeStartButton.disabled=false;routeStartButton.textContent=routeInstructions.length?'▶ Iniciar':'↗ Abrir en Maps';navStepIndex=0;routeHelp.textContent=routeInstructions.length?'Ruta calculada. Pulsa Iniciar para recibir indicaciones según tu ubicación.':'La ruta está lista para abrirse en Google Maps.'}catch(e){routeStartButton.disabled=false;routeStartButton.textContent='↗ Abrir en Maps';routeHelp.textContent='No se pudo calcular la guía aquí. Puedes abrir el recorrido en Google Maps.'}finally{btn.disabled=false;btn.textContent='Calcular ruta'}}
function distanceBetween(a,b){const rad=x=>x*Math.PI/180,R=6371000,dLat=rad(b[0]-a[0]),dLon=rad(b[1]-a[1]),lat1=rad(a[0]),lat2=rad(b[0]),h=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLon/2)**2;return 2*R*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function updateNavigation(pos){const loc=[pos.coords.latitude,pos.coords.longitude],firstFix=!navPositionMarker;navCurrentLocation=loc;routeStartButton.textContent='Ruta activa';if(!navPositionMarker)navPositionMarker=L.circleMarker(loc,{radius:8,color:'#fff',weight:3,fillColor:'#4285f4',fillOpacity:1}).addTo(map);else navPositionMarker.setLatLng(loc);navPositionMarker.bringToFront();if(firstFix&&followNavigation)map.flyTo(loc,17,{duration:.7});else if(followNavigation&&map.distance(loc,map.getCenter())>60)map.panTo(loc,{animate:true,duration:.4});if(followNavigation)document.getElementById('nav-recenter').hidden=true;while(navStepIndex+1<routeInstructions.length&&distanceBetween(loc,routeInstructions[navStepIndex+1].coord)<25)navStepIndex++;routeGuidance.querySelectorAll('.route-step[data-route-instruction]').forEach(row=>row.classList.toggle('active',Number(row.dataset.routeInstruction)===navStepIndex));const current=routeInstructions[navStepIndex];if(!current){navPrimary.textContent='Continúa por la ruta';navSecondary.textContent='';return}const arrived=current.step.maneuver?.type==='arrive';navPrimary.textContent=arrived?'Llegaste al destino':turnText(current.step);const next=routeInstructions[navStepIndex+1];if(next){const remaining=distanceBetween(loc,next.coord);navSecondary.textContent=(remaining<30?'Ahora: ':'En '+formatDistance(remaining)+', ')+turnText(next.step)}else navSecondary.textContent='Destino: '+routeStops[routeStops.length-1].name;hidePanel()}
function startNavigation(){if(!routeInstructions.length){if(routeStops.length<2){routeHelp.textContent='Añade al menos dos puntos para iniciar.';return}window.open(googleMapsRouteUrl(),'_blank','noopener,noreferrer');return}if(!navigator.geolocation){routeHelp.textContent='Este navegador no ofrece GPS.';return}stopNavigation();navigationActive=true;followNavigation=true;navStepIndex=0;navCard.hidden=false;navPrimary.textContent='Buscando tu ubicación…';navSecondary.textContent='Permite el acceso al GPS para iniciar la guía.';routeStartButton.disabled=true;routeStartButton.textContent='Buscando GPS…';hidePanel();navWatchId=navigator.geolocation.watchPosition(updateNavigation,err=>{if(err.code===1){routeHelp.textContent='Permite la ubicación GPS para iniciar la guía.';stopNavigation()}else navSecondary.textContent='Buscando señal GPS…'},{enableHighAccuracy:true,timeout:20000,maximumAge:3000})}
function parseCoordinate(q){let m=q.match(/^\s*(-?\d+(?:[.,]\d+)?)\s*[,; ]\s*(-?\d+(?:[.,]\d+)?)\s*$/);if(m){let a=Number(m[1].replace(',','.')),b=Number(m[2].replace(',','.'));if(Math.abs(a)<=90&&Math.abs(b)<=180)return [b,a];if(Math.abs(a)<=180&&Math.abs(b)<=90)return [a,b]}const re=/(\d+(?:[.,]\d+)?)\s*°\s*(\d+(?:[.,]\d+)?)\s*['′]\s*(\d+(?:[.,]\d+)?)\s*["″]?\s*([NSEW])/ig,parts=[...q.matchAll(re)];if(parts.length>=2){const nums=parts.slice(0,2).map(x=>{let v=Number(x[1].replace(',','.'))+Number(x[2].replace(',','.'))/60+Number(x[3].replace(',','.'))/3600;if(/[SW]/i.test(x[4]))v=-v;return [x[4].toUpperCase(),v]});const lat=nums.find(x=>/[NS]/.test(x[0]))?.[1],lon=nums.find(x=>/[EW]/.test(x[0]))?.[1];if(lat!==undefined&&lon!==undefined)return [lon,lat]}return null}
function showResults(items){searchResults.innerHTML='';for(const item of items.slice(0,15)){const b=document.createElement('button');b.className='result';b.textContent=item.title||item.layer;const small=document.createElement('small');small.textContent=item.layer+(item.subtitle?' · '+item.subtitle:'');b.appendChild(small);b.onclick=()=>{if(routeMode){const c=coordOf(item.geometry);if(c)addRouteStop(item.title||item.layer,c,item)}else goTo(item)};searchResults.appendChild(b)}if(items.length>15){const more=document.createElement('div');more.className='search-status';more.textContent='Mostrando 15 de '+items.length+' resultados';searchResults.appendChild(more)}}
function searchRank(item,q){const a=item.attrs||{},exact=(keys)=>keys.some(k=>norm(a[k])===q);if(item.layer==='Subestaciones'&&substationNumber(a.SE)&&norm(substationNumber(a.SE))===q)return 145;if(item.layer==='Subestaciones'&&exact(['SE']))return 140;if(item.layer==='Postes'&&exact(['IDENTIFICADOR_VNR','POSTE_ID']))return 135;if(item.layer==='Equipos'&&exact(['DENOMINACION','EQUIPO_ID']))return 135;if(item.layer==='Redes MT'&&exact(['TRAMO_MT_ID']))return 135;if(item.layer==='Red BT'&&exact(['TRAMO_BT_ID']))return 135;if(item.layer.startsWith('Concesión')&&exact(['ID','POLIGONAL_ID']))return 135;if(item.layer==='Subestaciones'&&norm(substationNumber(a.SE)).includes(q))return 110;if(item.layer==='Subestaciones'&&exact(['TRANSFORMADOR_ID']))return 105;if(item.layer==='Subestaciones'&&norm(a.TRANSFORMADOR_ID).includes(q))return 90;if(item.title&&norm(item.title)===q)return 100;if(item.layer==='Postes'&&norm(a.IDENTIFICADOR_VNR).includes(q))return 85;if(item.layer==='Equipos'&&(norm(a.DENOMINACION).includes(q)||norm(a.EQUIPO_ID).includes(q)))return 85;return 10}
async function runSearch(){const q=searchInput.value.trim();searchResults.innerHTML='';if(!q)return;const coord=parseCoordinate(q);if(coord){if(routeMode){addRouteStop('Coordenadas '+coord[1].toFixed(5)+', '+coord[0].toFixed(5),[coord[1],coord[0]]);return}hidePanel();map.flyTo([coord[1],coord[0]],16,{duration:0.9});if(selectedMarker)selectedMarker.remove();selectedMarker=L.circleMarker([coord[1],coord[0]],{renderer,radius:9,color:'#fff',weight:3,fillColor:'#4285f4',fillOpacity:1}).addTo(map);searchStatus.textContent='Coordenadas: '+coord[1].toFixed(6)+', '+coord[0].toFixed(6);return}const nq=norm(q),hits=searchIndex.filter(x=>x.search.includes(nq)).sort((a,b)=>searchRank(b,nq)-searchRank(a,nq));if(hits.length){searchStatus.textContent=hits.length+' elementos encontrados. Toca un resultado para ir.';showResults(hits);return}searchStatus.textContent='Buscando dirección o lugar en Punta Arenas…';try{const localQuery=q.replace(/\s*&\s*/g,' y ')+' Punta Arenas Chile',params=new URLSearchParams({q:localQuery,lat:'-53.15',lon:'-70.92',zoom:'12',location_bias_scale:'0.1',countrycode:'CL',limit:'8'});const response=await fetch('https://photon.komoot.io/api/?'+params.toString(),{headers:{'Accept':'application/geo+json'}});if(!response.ok)throw new Error('Photon HTTP '+response.status);const places=(await response.json()).features||[];if(!places.length){searchStatus.textContent='No encontré coincidencias en Punta Arenas.';return}searchStatus.textContent='Lugares encontrados · OpenStreetMap';showResults(places.map(p=>{const x=p.properties||{},label=x.housenumber?[x.name,x.housenumber,x.street,x.district].filter(Boolean).join(', '):[x.name,x.street,x.district||x.city].filter(Boolean).join(', ');return{title:label||'Lugar en el mapa',layer:'Lugar',geometry:{type:'Point',coordinates:p.geometry.coordinates}}}))}catch(e){console.error('Error de búsqueda de direcciones:',e);searchStatus.textContent='No se pudo consultar el buscador de direcciones. Inténtalo nuevamente.'}}
document.getElementById('search-go').onclick=runSearch;searchInput.addEventListener('keydown',e=>{if(e.key==='Enter')runSearch()});
document.getElementById('gps').onclick=()=>{if(!navigator.geolocation){searchStatus.textContent='Este navegador no ofrece GPS.';return}searchStatus.textContent='Solicitando ubicación al navegador…';navigator.geolocation.getCurrentPosition(pos=>{const c=[pos.coords.latitude,pos.coords.longitude];hidePanel();map.flyTo(c,17,{duration:0.9});if(gpsMarker)gpsMarker.remove();gpsMarker=L.marker(c).addTo(map).bindPopup('Tu ubicación actual'+popupActions('Lugar',{},c)).openPopup();searchStatus.textContent='Ubicación actual'},err=>{searchStatus.textContent=err.code===1?'Permite la ubicación. En el celular se requiere HTTPS para habilitar GPS.':'No se pudo obtener la ubicación GPS.'},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})};
function setMapStyle(style){satelliteOn=style==='satellite';if(satelliteOn){map.removeLayer(osm);map.addLayer(satellite)}else{map.removeLayer(satellite);map.addLayer(osm)}document.getElementById('style-satellite').classList.toggle('active',satelliteOn);document.getElementById('style-satellite').setAttribute('aria-pressed',String(satelliteOn));document.getElementById('style-streets').classList.toggle('active',!satelliteOn);document.getElementById('style-streets').setAttribute('aria-pressed',String(!satelliteOn))}document.getElementById('style-satellite').onclick=()=>setMapStyle('satellite');document.getElementById('style-streets').onclick=()=>setMapStyle('streets');setMapStyle('satellite');
const layerControls=document.getElementById('layer-list'),allBounds=[];
for(const LYR of layers){const d=LYR.data,group=L.layerGroup(),color=LYR.color||'#607d8b';const items=[];
 for(const f of d.points){const props={name:f.name||'',attrs:f.attributes||{},description:f.description||''},text=[props.name,props.description,searchableAttrs(props.attrs)].join(' '),icon=symbolType(LYR.name,props.attrs);items.push({title:assetTitle(LYR.name,props.attrs,props.name),subtitle:assetSubtitle(LYR.name,props.attrs),layer:LYR.name,attrs:props.attrs,assetIcon:icon,search:norm(text+' '+LYR.name),geometry:{type:'Point',coordinates:f.coordinates}});const ll=[f.coordinates[1],f.coordinates[0]],marker=L.circleMarker(ll,{renderer,radius:9,color:'#333',weight:1,fillColor:f.color||color,fillOpacity:0.98,assetIcon:icon});wireAssetPopup(marker,LYR.name,props.attrs,props.name,ll);marker.on('click',hidePanel);marker.on('dblclick',e=>{L.DomEvent.stop(e);map.flyTo(ll,17,{duration:0.8});marker.openPopup()});group.addLayer(marker)}
 if(d.lines.length){const coords=d.lines.map(f=>f.coordinates.map(c=>[c[1],c[0]]));group.addLayer(L.polyline(coords,{renderer,color:LYR.id==='network-3'?'#ff3030':LYR.id==='network-4'?'#1646ff':color,weight:2,opacity:0.95,interactive:false}));for(const f of d.lines){const attrs=f.attributes||{},text=[f.name,f.description,searchableAttrs(attrs)].join(' ');items.push({title:assetTitle(LYR.name,attrs,f.name),subtitle:assetSubtitle(LYR.name,attrs),layer:LYR.name,attrs,search:norm(text+' '+LYR.name),geometry:{type:'LineString',coordinates:f.coordinates}})}}
 for(const f of d.polygons){const latlngs=f.coordinates.map(r=>r.map(c=>[c[1],c[0]]));const poly=L.polygon(latlngs,{renderer,color,weight:1.5,fillColor:color,fillOpacity:0.25,interactive:false});group.addLayer(poly);const attrs=f.attributes||{},text=[f.name,f.description,searchableAttrs(attrs)].join(' ');items.push({title:assetTitle(LYR.name,attrs,f.name),subtitle:assetSubtitle(LYR.name,attrs),layer:LYR.name,attrs,search:norm(text+' '+LYR.name),geometry:{type:'Polygon',coordinates:f.coordinates}})}
 for(const item of items){if(item.geometry.type==='Point'||item.geometry.type==='LineString')searchIndex.push(item);else searchIndex.push(item)}
 const defaultOn=LYR.id.startsWith('network-');const row=document.createElement('div');row.innerHTML='<label class="row"><input type="checkbox" '+(defaultOn?'checked':'')+'><span class="swatch" style="background:'+color+'"></span><span>'+LYR.name+'</span></label><span class="count">'+items.length.toLocaleString('es-CL')+' elementos</span>';const check=row.querySelector('input');check.onchange=()=>check.checked?map.addLayer(group):map.removeLayer(group);layerControls.appendChild(row);if(defaultOn)map.addLayer(group);if(LYR.id.startsWith('network-')){const bounds=group.getBounds?.();if(bounds&&bounds.isValid())allBounds.push(bounds)}}
if(allBounds.length){const b=allBounds.reduce((acc,x)=>acc.extend(x),L.latLngBounds(allBounds[0]));map.fitBounds(b.pad(0.03),{maxZoom:12})}
</script></body></html>""".replace("__LAYERS__", layers_json)

components.html(html, height=850, scrolling=False)
